# Configuración básica
sonar.projectKey=KIERT-FRONTEND
sonar.projectName=KIERT-FRONTEND
sonar.projectVersion=1.0.0

# Fuentes
sonar.sources=src
sonar.sourceEncoding=UTF-8

# Exclusión de archivos sensibles y builds
sonar.exclusions=**/node_modules/**, **/dist/**, **/*.spec.ts, **/*.test.ts, **/environments/**, **/assets/**

# Cobertura
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.spec.ts, **/*.test.ts, **/environments/**/*.ts, **/interceptors/*.ts, **/app.config.ts

# Ignorar credenciales hardcodeadas en archivos de entorno
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S2068
sonar.issue.ignore.multicriteria.e1.resourceKey=**/environments/*.ts

# Pruebas
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts, **/*.test.ts
sonar.junit.reportPaths=test-results/junit.xml

# Angular
sonar.angular.version=17.0.0
sonar.javascript.node.maxspace=4096